"""
Django settings for smart_trip_planner project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# A3.3: directory for log files (LLM call telemetry). Created if missing.
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zwdz6#0nh40$d7&f-cp!s_$oi9lddhdew$8kg-b(h(c(c$ib_r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'trips',
    'agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smart_trip_planner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_trip_planner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'resurse',
]

LOGIN_URL = 'login'

# A3.1: run the Data Architect (Agent 2) in a background thread so the user gets
# the Concierge reply immediately. Set False (e.g. in tests) to run inline.
AGENTS_RUN_ASYNC = True

# A3.4: RapidAPI-backed tools for real flight/hotel data (Concierge tools).
# All optional: without a key the Concierge falls back to estimate-based answers.
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY', '')
# Flights use a separate listing (google-flights2) with its own subscription, so
# they get their own key; falls back to RAPIDAPI_KEY if unset.
RAPIDAPI_FLIGHTS_KEY = os.getenv('RAPIDAPI_FLIGHTS_KEY', '') or RAPIDAPI_KEY
RAPIDAPI_FLIGHTS_HOST = os.getenv('RAPIDAPI_FLIGHTS_HOST', '')
RAPIDAPI_HOTELS_HOST = os.getenv('RAPIDAPI_HOTELS_HOST', '')
# Endpoint paths (defaults filled after probing the chosen listings).
RAPIDAPI_FLIGHTS_PATH = os.getenv('RAPIDAPI_FLIGHTS_PATH', '')
RAPIDAPI_HOTELS_PATH = os.getenv('RAPIDAPI_HOTELS_PATH', '')

# A3.3: log every LLM call (model, tokens, latency, success/fail) to a file.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '%(asctime)s %(levelname)s %(name)s %(message)s'},
        'llm': {'format': '%(asctime)s %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'llm_file': {
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'llm_calls.log'),
            'formatter': 'llm',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Agent logs (orchestrator, concierge, data_architect) → console.
        'agents': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        # Per-call LLM telemetry → file (and console for convenience).
        'agents.llm': {'handlers': ['llm_file', 'console'], 'level': 'INFO', 'propagate': False},
        # A3.4: external tool (RapidAPI) call telemetry → same file + console.
        'agents.tools': {'handlers': ['llm_file', 'console'], 'level': 'INFO', 'propagate': False},
    },
}
