# Generated by Django 6.0.4 on 2026-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='ai_updated_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
