# Generated by Django 6.0.4 on 2026-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreference_ai_updated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='hotel_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
